name: Create Android Folder

on:
  workflow_dispatch:   # يخلي عندك زر Run workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'   # تحدد نسخة Flutter

      - name: Create Android folder
        run: flutter create .
