name: Create Android Project

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Search for WRONG package anywhere
        run: |
          echo "Searching for 'flutter_native_timezone_updated' ..."
          grep -R --line-number "flutter_native_timezone_updated" . || echo "NOT FOUND"

      - name: Show pubspec.yaml content
        run: cat pubspec.yaml

      - name: Create Android folder
        run: flutter create .
