name: Create Android Project

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show repo info
        run: |
          echo "BRANCH = $GITHUB_REF"
          echo "PWD = $(pwd)"
          ls -la

      - name: Search for WRONG package anywhere
        run: |
          echo "Searching for 'flutter_native_timezone_updated' ..."
          grep -R --line-number "flutter_native_timezone_updated" . || echo "NOT FOUND"

      - name: Show pubspec BEFORE
        run: |
          echo "======== pubspec.yaml (BEFORE) ========"
          cat pubspec.yaml || echo "pubspec.yaml NOT FOUND!"
          echo "======================================="

      # إصلاح تلقائي للاسم الغلط داخل مساحة العمل (مع commit + push)
      - name: Fix wrong timezone package name if present
        run: |
          set -e
          if grep -q "flutter_native_timezone_updated" pubspec.yaml; then
            echo ">> Found WRONG package name. Fixing and committing..."
            # استبدال السطر إن كان معه نسخة
            sed -i -E 's/flutter_native_timezone_updated:[^\r\n]*/flutter_native_timezone: ^2.0.0/' pubspec.yaml
            # واستبدال أي بقايا للكلمة
            sed -i -E 's/flutter_native_timezone_updated/flutter_native_timezone/g' pubspec.yaml
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add pubspec.yaml
            git commit -m "Fix pubspec: use flutter_native_timezone instead of *_updated"
            git push
          else
            echo ">> Package name already correct."
          fi

      - name: Show pubspec AFTER
        run: |
          echo "======== pubspec.yaml (AFTER) ========="
          cat pubspec.yaml
          echo "======================================="

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Create Android folder if missing
        run: |
          if [ ! -d "android" ]; then
            flutter create .
          else
            echo "Android folder already exists."
          fi

      - name: Flutter pub get
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: zakkirni-app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
